import { Question, DifficultyLevel } from '@/types/demo';

/**
 * Expanded question bank with English and Critical Thinking/Programming
 * Same quality and structure as math questions
 */

// ENGLISH LANGUAGE QUESTIONS
export const englishQuestions: Record<DifficultyLevel, Question[]> = {
  beginner: [
    {
      id: 'eng-beg-vocab-1',
      text: 'Which word means the opposite of "hot"?',
      answers: ['warm', 'cold', 'cool', 'freeze'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'vocabulary',
      voiceText: 'Which word means the opposite of hot?',
      hint: 'Think about ice cream!',
    },
    {
      id: 'eng-beg-vocab-2',
      text: 'Which word means a baby dog?',
      answers: ['kitten', 'puppy', 'calf', 'chick'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'vocabulary',
      voiceText: 'Which word means a baby dog?',
      hint: 'It starts with P!',
    },
    {
      id: 'eng-beg-gram-1',
      text: 'Which sentence is correct?',
      answers: ['I am happy', 'I is happy', 'I are happy', 'I be happy'],
      correctIndex: 0,
      difficulty: 'beginner',
      topic: 'grammar',
      voiceText: 'Which sentence is correct?',
      hint: 'Use "am" with "I"',
    },
    {
      id: 'eng-beg-gram-2',
      text: 'What comes at the end of a sentence?',
      answers: ['comma', 'period', 'question', 'letter'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'grammar',
      voiceText: 'What comes at the end of a sentence?',
      hint: 'It looks like a dot!',
    },
  ],

  easy: [
    {
      id: 'eng-easy-vocab-1',
      text: 'Which word means "very big"?',
      answers: ['tiny', 'huge', 'small', 'little'],
      correctIndex: 1,
      difficulty: 'easy',
      topic: 'vocabulary',
      voiceText: 'Which word means very big?',
      hint: 'Think of an elephant!',
    },
    {
      id: 'eng-easy-vocab-2',
      text: 'What is a synonym for "happy"?',
      answers: ['sad', 'angry', 'joyful', 'tired'],
      correctIndex: 2,
      difficulty: 'easy',
      topic: 'vocabulary',
      voiceText: 'What is a synonym for happy?',
      hint: 'Another word that means the same!',
    },
    {
      id: 'eng-easy-gram-1',
      text: 'Which word is a noun?',
      answers: ['run', 'quickly', 'dog', 'happy'],
      correctIndex: 2,
      difficulty: 'easy',
      topic: 'grammar',
      voiceText: 'Which word is a noun?',
      hint: 'A noun is a person, place, or thing!',
    },
    {
      id: 'eng-easy-read-1',
      text: '"The cat sat on the mat." Where did the cat sit?',
      answers: ['on the hat', 'on the mat', 'on the bat', 'on the rat'],
      correctIndex: 1,
      difficulty: 'easy',
      topic: 'reading',
      voiceText: 'The cat sat on the mat. Where did the cat sit?',
      hint: 'Read carefully!',
    },
  ],

  medium: [
    {
      id: 'eng-med-vocab-1',
      text: 'Which word means "to make better"?',
      answers: ['worsen', 'improve', 'damage', 'break'],
      correctIndex: 1,
      difficulty: 'medium',
      topic: 'vocabulary',
      voiceText: 'Which word means to make better?',
      hint: 'Think about getting a better grade!',
    },
    {
      id: 'eng-med-gram-1',
      text: 'Which sentence uses the correct verb tense?',
      answers: ['I goed to school', 'I go to school yesterday', 'I went to school yesterday', 'I going to school yesterday'],
      correctIndex: 2,
      difficulty: 'medium',
      topic: 'grammar',
      voiceText: 'Which sentence uses the correct verb tense?',
      hint: 'Past tense of "go" is irregular!',
    },
    {
      id: 'eng-med-read-1',
      text: '"Sarah loves reading books. She reads every night before bed." What can we infer about Sarah?',
      answers: ['She dislikes books', 'She enjoys reading', 'She never reads', 'She only reads in the morning'],
      correctIndex: 1,
      difficulty: 'medium',
      topic: 'reading',
      voiceText: 'Sarah loves reading books. She reads every night before bed. What can we infer about Sarah?',
      hint: 'What does "loves" tell us?',
    },
    {
      id: 'eng-med-gram-2',
      text: 'Which word is an adjective?',
      answers: ['quickly', 'beautiful', 'run', 'happiness'],
      correctIndex: 1,
      difficulty: 'medium',
      topic: 'grammar',
      voiceText: 'Which word is an adjective?',
      hint: 'Adjectives describe nouns!',
    },
  ],

  hard: [
    {
      id: 'eng-hard-vocab-1',
      text: 'What does "meticulous" mean?',
      answers: ['careless', 'very careful and precise', 'fast', 'lazy'],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'vocabulary',
      voiceText: 'What does meticulous mean?',
      hint: 'Think about someone who pays attention to every detail!',
    },
    {
      id: 'eng-hard-gram-1',
      text: 'Which sentence correctly uses a semicolon?',
      answers: [
        'I like apples; but not oranges',
        'I like apples; oranges are okay too',
        'I like; apples and oranges',
        'I like apples and; oranges'
      ],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'grammar',
      voiceText: 'Which sentence correctly uses a semicolon?',
      hint: 'Semicolons connect related independent clauses!',
    },
    {
      id: 'eng-hard-read-1',
      text: '"Despite the rain, the game continued." What does "despite" mean here?',
      answers: ['because of', 'even though there was', 'after', 'before'],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'reading',
      voiceText: 'Despite the rain, the game continued. What does despite mean here?',
      hint: 'It shows contrast!',
    },
    {
      id: 'eng-hard-write-1',
      text: 'Which sentence has the best parallel structure?',
      answers: [
        'She likes swimming, to bike, and running',
        'She likes swimming, biking, and running',
        'She likes to swim, biking, and to run',
        'She likes swim, bike, and run'
      ],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'writing',
      voiceText: 'Which sentence has the best parallel structure?',
      hint: 'All verbs should have the same form!',
    },
  ],
};

// CRITICAL THINKING / PROGRAMMING QUESTIONS
export const logicQuestions: Record<DifficultyLevel, Question[]> = {
  beginner: [
    {
      id: 'log-beg-pat-1',
      text: 'What comes next? 🔴 🔵 🔴 🔵 🔴 ?',
      answers: ['🔴', '🔵', '🟢', '🟡'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'patterns',
      voiceText: 'What comes next in this pattern? Red, blue, red, blue, red...',
      hint: 'The pattern repeats: red, blue, red, blue...',
    },
    {
      id: 'log-beg-pat-2',
      text: 'Complete the pattern: 1, 2, 1, 2, 1, ?',
      answers: ['1', '2', '3', '4'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'patterns',
      voiceText: 'Complete the pattern: 1, 2, 1, 2, 1...',
      hint: 'It alternates between 1 and 2!',
    },
    {
      id: 'log-beg-seq-1',
      text: 'What number comes next? 2, 4, 6, 8, ?',
      answers: ['9', '10', '11', '12'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'sequences',
      voiceText: 'What number comes next? 2, 4, 6, 8...',
      hint: 'Count by 2s!',
    },
    {
      id: 'log-beg-log-1',
      text: 'If all cats have tails, and Fluffy is a cat, then...',
      answers: ['Fluffy has no tail', 'Fluffy has a tail', 'Fluffy is a dog', 'Cats have no tails'],
      correctIndex: 1,
      difficulty: 'beginner',
      topic: 'logic',
      voiceText: 'If all cats have tails, and Fluffy is a cat, then what?',
      hint: 'If ALL cats have tails, what about Fluffy?',
    },
  ],

  easy: [
    {
      id: 'log-easy-pat-1',
      text: 'What comes next? ⭐⭐🌙 ⭐⭐🌙 ⭐⭐?',
      answers: ['⭐', '🌙', '☀️', '🌟'],
      correctIndex: 1,
      difficulty: 'easy',
      topic: 'patterns',
      voiceText: 'What comes next? Star, star, moon, star, star, moon, star, star...',
      hint: 'The pattern is: star, star, moon!',
    },
    {
      id: 'log-easy-seq-1',
      text: 'What number is missing? 5, 10, ?, 20, 25',
      answers: ['12', '13', '15', '18'],
      correctIndex: 2,
      difficulty: 'easy',
      topic: 'sequences',
      voiceText: 'What number is missing? 5, 10, blank, 20, 25',
      hint: 'Count by 5s!',
    },
    {
      id: 'log-easy-prog-1',
      text: 'In programming, what does a "loop" do?',
      answers: ['Stops the program', 'Repeats actions', 'Deletes code', 'Prints once'],
      correctIndex: 1,
      difficulty: 'easy',
      topic: 'programming',
      voiceText: 'In programming, what does a loop do?',
      hint: 'Think about doing something over and over!',
    },
    {
      id: 'log-easy-log-1',
      text: 'If it rains, the ground gets wet. The ground is wet. What can we conclude?',
      answers: ['It definitely rained', 'It might have rained', 'It did not rain', 'The ground is dry'],
      correctIndex: 1,
      difficulty: 'easy',
      topic: 'logic',
      voiceText: 'If it rains, the ground gets wet. The ground is wet. What can we conclude?',
      hint: 'Could something else make the ground wet?',
    },
  ],

  medium: [
    {
      id: 'log-med-pat-1',
      text: 'What comes next? 2, 4, 8, 16, ?',
      answers: ['18', '20', '24', '32'],
      correctIndex: 3,
      difficulty: 'medium',
      topic: 'patterns',
      voiceText: 'What comes next? 2, 4, 8, 16...',
      hint: 'Each number is double the previous!',
    },
    {
      id: 'log-med-seq-1',
      text: 'Find the pattern: 1, 1, 2, 3, 5, 8, ?',
      answers: ['11', '12', '13', '14'],
      correctIndex: 2,
      difficulty: 'medium',
      topic: 'sequences',
      voiceText: 'Find the pattern: 1, 1, 2, 3, 5, 8...',
      hint: 'Add the previous two numbers!',
    },
    {
      id: 'log-med-prog-1',
      text: 'What will this code print? for i in range(3): print(i)',
      answers: ['1 2 3', '0 1 2', '3 3 3', '0 0 0'],
      correctIndex: 1,
      difficulty: 'medium',
      topic: 'programming',
      voiceText: 'What will this code print? for i in range 3, print i',
      hint: 'Computers start counting at 0!',
    },
    {
      id: 'log-med-log-1',
      text: 'All squares are rectangles. Some rectangles are blue. Therefore...',
      answers: ['All squares are blue', 'Some squares might be blue', 'No squares are blue', 'All rectangles are squares'],
      correctIndex: 1,
      difficulty: 'medium',
      topic: 'logic',
      voiceText: 'All squares are rectangles. Some rectangles are blue. Therefore what?',
      hint: 'We can\'t be certain about all squares!',
    },
  ],

  hard: [
    {
      id: 'log-hard-pat-1',
      text: 'What comes next? 1, 4, 9, 16, 25, ?',
      answers: ['30', '35', '36', '40'],
      correctIndex: 2,
      difficulty: 'hard',
      topic: 'patterns',
      voiceText: 'What comes next? 1, 4, 9, 16, 25...',
      hint: 'These are perfect squares: 1², 2², 3²...',
    },
    {
      id: 'log-hard-seq-1',
      text: 'Find the next number: 2, 6, 12, 20, 30, ?',
      answers: ['40', '42', '44', '48'],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'sequences',
      voiceText: 'Find the next number: 2, 6, 12, 20, 30...',
      hint: 'Differences are: 4, 6, 8, 10... what\'s next?',
    },
    {
      id: 'log-hard-prog-1',
      text: 'What is the output? x = 5; if x > 3: x = x * 2; print(x)',
      answers: ['3', '5', '10', '15'],
      correctIndex: 2,
      difficulty: 'hard',
      topic: 'programming',
      voiceText: 'What is the output? x equals 5, if x is greater than 3, x equals x times 2, print x',
      hint: 'Check the condition, then do the operation!',
    },
    {
      id: 'log-hard-log-1',
      text: 'If A→B and B→C, what can we conclude?',
      answers: ['C→A', 'A→C', 'B→A', 'Nothing'],
      correctIndex: 1,
      difficulty: 'hard',
      topic: 'logic',
      voiceText: 'If A implies B, and B implies C, what can we conclude?',
      hint: 'This is called transitive property!',
    },
  ],
};

// Combine all question banks
export const allQuestions: Record<DifficultyLevel, Question[]> = {
  beginner: [
    ...englishQuestions.beginner,
    ...logicQuestions.beginner,
  ],
  easy: [
    ...englishQuestions.easy,
    ...logicQuestions.easy,
  ],
  medium: [
    ...englishQuestions.medium,
    ...logicQuestions.medium,
  ],
  hard: [
    ...englishQuestions.hard,
    ...logicQuestions.hard,
  ],
};
