/**
 * AgentGeneratedContent Component
 * 
 * Displays content generated by AI agents with appropriate styling and interactions.
 * Supports lessons, quizzes, activities, and recommendations.
 */

'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  BookOpen, 
  Brain, 
  Gamepad2, 
  CheckCircle, 
  XCircle, 
  Lightbulb,
  Sparkles,
  ArrowRight
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export type AgentContentType = 'lesson' | 'quiz' | 'activity' | 'recommendation' | 'intervention';

export interface AgentContent {
  id: string;
  type: AgentContentType;
  title: string;
  description?: string;
  content: any;
  metadata?: {
    difficulty?: string;
    estimatedTime?: number;
    learningObjectives?: string[];
    generatedBy?: string;
  };
}

interface AgentGeneratedContentProps {
  content: AgentContent;
  onComplete?: (result: any) => void;
  onDismiss?: () => void;
  className?: string;
}

export function AgentGeneratedContent({
  content,
  onComplete,
  onDismiss,
  className = '',
}: AgentGeneratedContentProps) {
  const [isCompleted, setIsCompleted] = useState(false);
  const [userResponse, setUserResponse] = useState<any>(null);

  const getIcon = () => {
    switch (content.type) {
      case 'lesson':
        return <BookOpen className="w-6 h-6" />;
      case 'quiz':
        return <Brain className="w-6 h-6" />;
      case 'activity':
        return <Gamepad2 className="w-6 h-6" />;
      case 'recommendation':
        return <Lightbulb className="w-6 h-6" />;
      case 'intervention':
        return <Sparkles className="w-6 h-6" />;
      default:
        return <BookOpen className="w-6 h-6" />;
    }
  };

  const getColorScheme = () => {
    switch (content.type) {
      case 'lesson':
        return {
          bg: 'from-blue-50 to-cyan-50',
          border: 'border-blue-300',
          icon: 'bg-blue-100 text-blue-600',
          button: 'from-blue-500 to-cyan-500',
        };
      case 'quiz':
        return {
          bg: 'from-purple-50 to-pink-50',
          border: 'border-purple-300',
          icon: 'bg-purple-100 text-purple-600',
          button: 'from-purple-500 to-pink-500',
        };
      case 'activity':
        return {
          bg: 'from-green-50 to-teal-50',
          border: 'border-green-300',
          icon: 'bg-green-100 text-green-600',
          button: 'from-green-500 to-teal-500',
        };
      case 'recommendation':
        return {
          bg: 'from-yellow-50 to-orange-50',
          border: 'border-yellow-300',
          icon: 'bg-yellow-100 text-yellow-600',
          button: 'from-yellow-500 to-orange-500',
        };
      case 'intervention':
        return {
          bg: 'from-pink-50 to-rose-50',
          border: 'border-pink-300',
          icon: 'bg-pink-100 text-pink-600',
          button: 'from-pink-500 to-rose-500',
        };
      default:
        return {
          bg: 'from-gray-50 to-slate-50',
          border: 'border-gray-300',
          icon: 'bg-gray-100 text-gray-600',
          button: 'from-gray-500 to-slate-500',
        };
    }
  };

  const colors = getColorScheme();

  const handleComplete = (result: any) => {
    setIsCompleted(true);
    setUserResponse(result);
    onComplete?.(result);
  };

  const renderContent = () => {
    switch (content.type) {
      case 'lesson':
        return <LessonContent content={content.content} onComplete={handleComplete} />;
      case 'quiz':
        return <QuizContent content={content.content} onComplete={handleComplete} />;
      case 'activity':
        return <ActivityContent content={content.content} onComplete={handleComplete} />;
      case 'recommendation':
        return <RecommendationContent content={content.content} onDismiss={onDismiss} />;
      case 'intervention':
        return <InterventionContent content={content.content} onDismiss={onDismiss} />;
      default:
        return <div className="text-gray-600">{JSON.stringify(content.content)}</div>;
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`bg-gradient-to-br ${colors.bg} rounded-2xl border-2 ${colors.border} shadow-[4px_4px_0px_0px_rgba(0,0,0,0.1)] p-6 ${className}`}
    >
      {/* Header */}
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className={`${colors.icon} p-3 rounded-xl border-2 border-black`}>
            {getIcon()}
          </div>
          <div>
            <h3 className="text-lg font-black text-gray-900">{content.title}</h3>
            {content.description && (
              <p className="text-sm text-gray-600 mt-1">{content.description}</p>
            )}
          </div>
        </div>
        {isCompleted && (
          <div className="bg-green-100 p-2 rounded-lg border-2 border-green-400">
            <CheckCircle className="w-5 h-5 text-green-600" />
          </div>
        )}
      </div>

      {/* Metadata */}
      {content.metadata && (
        <div className="flex flex-wrap gap-2 mb-4">
          {content.metadata.difficulty && (
            <span className="px-3 py-1 bg-white rounded-full text-xs font-bold border-2 border-black">
              {content.metadata.difficulty}
            </span>
          )}
          {content.metadata.estimatedTime && (
            <span className="px-3 py-1 bg-white rounded-full text-xs font-bold border-2 border-black">
              ⏱️ {content.metadata.estimatedTime} min
            </span>
          )}
          {content.metadata.generatedBy && (
            <span className="px-3 py-1 bg-white rounded-full text-xs font-bold border-2 border-black">
              🤖 {content.metadata.generatedBy}
            </span>
          )}
        </div>
      )}

      {/* Content */}
      <div className="bg-white rounded-xl border-2 border-black p-4">
        {renderContent()}
      </div>

      {/* Learning Objectives */}
      {content.metadata?.learningObjectives && content.metadata.learningObjectives.length > 0 && (
        <div className="mt-4 p-3 bg-white/50 rounded-lg border border-gray-300">
          <p className="text-xs font-bold text-gray-700 mb-2">📚 What you'll learn:</p>
          <ul className="space-y-1">
            {content.metadata.learningObjectives.map((objective, index) => (
              <li key={index} className="text-xs text-gray-600 flex items-start gap-2">
                <span className="text-blue-600">•</span>
                <span>{objective}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </motion.div>
  );
}

// Sub-components for different content types

function LessonContent({ content, onComplete }: { content: any; onComplete: (result: any) => void }) {
  return (
    <div className="space-y-4">
      <div className="prose prose-sm max-w-none">
        {typeof content === 'string' ? (
          <p>{content}</p>
        ) : (
          <div dangerouslySetInnerHTML={{ __html: content.html || content.text || '' }} />
        )}
      </div>
      <Button
        onClick={() => onComplete({ completed: true, timestamp: Date.now() })}
        className="w-full bg-gradient-to-r from-blue-500 to-cyan-500 text-white font-bold"
      >
        Continue Learning <ArrowRight className="w-4 h-4 ml-2" />
      </Button>
    </div>
  );
}

function QuizContent({ content, onComplete }: { content: any; onComplete: (result: any) => void }) {
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);

  const handleSubmit = () => {
    if (!selectedAnswer) return;
    
    const isCorrect = selectedAnswer === content.correctAnswer;
    setIsSubmitted(true);
    onComplete({
      answer: selectedAnswer,
      correct: isCorrect,
      timestamp: Date.now(),
    });
  };

  return (
    <div className="space-y-4">
      <p className="font-bold text-gray-900">{content.question}</p>
      
      <div className="space-y-2">
        {content.options?.map((option: string, index: number) => (
          <button
            key={index}
            onClick={() => !isSubmitted && setSelectedAnswer(option)}
            disabled={isSubmitted}
            className={`w-full text-left p-3 rounded-lg border-2 font-semibold transition-all ${
              isSubmitted
                ? option === content.correctAnswer
                  ? 'bg-green-100 border-green-400 text-green-800'
                  : option === selectedAnswer
                  ? 'bg-red-100 border-red-400 text-red-800'
                  : 'bg-gray-50 border-gray-300 text-gray-600'
                : selectedAnswer === option
                ? 'bg-blue-100 border-blue-400 text-blue-800'
                : 'bg-white border-gray-300 text-gray-700 hover:border-blue-300'
            }`}
          >
            {option}
            {isSubmitted && option === content.correctAnswer && ' ✓'}
            {isSubmitted && option === selectedAnswer && option !== content.correctAnswer && ' ✗'}
          </button>
        ))}
      </div>

      {!isSubmitted ? (
        <Button
          onClick={handleSubmit}
          disabled={!selectedAnswer}
          className="w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white font-bold"
        >
          Submit Answer
        </Button>
      ) : (
        <div className={`p-3 rounded-lg border-2 ${
          selectedAnswer === content.correctAnswer
            ? 'bg-green-50 border-green-400'
            : 'bg-orange-50 border-orange-400'
        }`}>
          <p className="text-sm font-semibold text-gray-900 mb-1">
            {selectedAnswer === content.correctAnswer ? '🎉 Correct!' : '💡 Not quite!'}
          </p>
          <p className="text-sm text-gray-700">{content.explanation}</p>
        </div>
      )}
    </div>
  );
}

function ActivityContent({ content, onComplete }: { content: any; onComplete: (result: any) => void }) {
  return (
    <div className="space-y-4">
      <p className="text-gray-700">{content.description || content.text || 'Complete this activity!'}</p>
      <Button
        onClick={() => onComplete({ completed: true, timestamp: Date.now() })}
        className="w-full bg-gradient-to-r from-green-500 to-teal-500 text-white font-bold"
      >
        Start Activity <ArrowRight className="w-4 h-4 ml-2" />
      </Button>
    </div>
  );
}

function RecommendationContent({ content, onDismiss }: { content: any; onDismiss?: () => void }) {
  return (
    <div className="space-y-4">
      <p className="text-gray-700">{content.message || content.text || content.description}</p>
      {onDismiss && (
        <Button
          onClick={onDismiss}
          variant="outline"
          className="w-full border-2 border-black font-bold"
        >
          Got it!
        </Button>
      )}
    </div>
  );
}

function InterventionContent({ content, onDismiss }: { content: any; onDismiss?: () => void }) {
  return (
    <div className="space-y-4">
      <p className="text-gray-700 font-semibold">{content.message || content.text}</p>
      {content.suggestions && content.suggestions.length > 0 && (
        <ul className="space-y-2">
          {content.suggestions.map((suggestion: string, index: number) => (
            <li key={index} className="flex items-start gap-2 text-sm text-gray-600">
              <span className="text-pink-600">💡</span>
              <span>{suggestion}</span>
            </li>
          ))}
        </ul>
      )}
      {onDismiss && (
        <Button
          onClick={onDismiss}
          className="w-full bg-gradient-to-r from-pink-500 to-rose-500 text-white font-bold"
        >
          Thanks, Sunny!
        </Button>
      )}
    </div>
  );
}
