/**
 * AgentContentReview Component
 * 
 * Teacher interface for reviewing and approving content generated by AI agents.
 * Provides workflow for content moderation and quality control.
 */

'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  CheckCircle,
  XCircle,
  Edit,
  Eye,
  ThumbsUp,
  ThumbsDown,
  AlertCircle,
  BookOpen,
  Brain,
  Gamepad2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export interface GeneratedContentItem {
  id: string;
  type: 'lesson' | 'quiz' | 'activity';
  title: string;
  description: string;
  content: any;
  generatedBy: string;
  generatedAt: Date;
  status: 'pending' | 'approved' | 'rejected' | 'needs_revision';
  studentId?: string;
  metadata?: {
    difficulty?: string;
    topic?: string;
    learningObjectives?: string[];
  };
}

interface AgentContentReviewProps {
  contentItems: GeneratedContentItem[];
  onApprove: (id: string, feedback?: string) => void;
  onReject: (id: string, reason: string) => void;
  onRequestRevision: (id: string, notes: string) => void;
  className?: string;
}

export function AgentContentReview({
  contentItems,
  onApprove,
  onReject,
  onRequestRevision,
  className = '',
}: AgentContentReviewProps) {
  const [selectedItem, setSelectedItem] = useState<GeneratedContentItem | null>(null);
  const [reviewNotes, setReviewNotes] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'pending' | 'approved' | 'rejected'>('all');

  const filteredItems = contentItems.filter(item =>
    filterStatus === 'all' || item.status === filterStatus
  );

  const pendingCount = contentItems.filter(item => item.status === 'pending').length;

  const getIcon = (type: string) => {
    switch (type) {
      case 'lesson':
        return <BookOpen className="w-5 h-5" />;
      case 'quiz':
        return <Brain className="w-5 h-5" />;
      case 'activity':
        return <Gamepad2 className="w-5 h-5" />;
      default:
        return <BookOpen className="w-5 h-5" />;
    }
  };

  const getStatusBadge = (status: string) => {
    const badges = {
      pending: { bg: 'bg-yellow-100', text: 'text-yellow-700', border: 'border-yellow-300', label: 'Pending Review' },
      approved: { bg: 'bg-green-100', text: 'text-green-700', border: 'border-green-300', label: 'Approved' },
      rejected: { bg: 'bg-red-100', text: 'text-red-700', border: 'border-red-300', label: 'Rejected' },
      needs_revision: { bg: 'bg-orange-100', text: 'text-orange-700', border: 'border-orange-300', label: 'Needs Revision' },
    };

    const badge = badges[status as keyof typeof badges] || badges.pending;

    return (
      <span className={`px-3 py-1 rounded-full text-xs font-bold border ${badge.bg} ${badge.text} ${badge.border}`}>
        {badge.label}
      </span>
    );
  };

  const handleApprove = () => {
    if (selectedItem) {
      onApprove(selectedItem.id, reviewNotes);
      setSelectedItem(null);
      setReviewNotes('');
    }
  };

  const handleReject = () => {
    if (selectedItem && reviewNotes.trim()) {
      onReject(selectedItem.id, reviewNotes);
      setSelectedItem(null);
      setReviewNotes('');
    }
  };

  const handleRequestRevision = () => {
    if (selectedItem && reviewNotes.trim()) {
      onRequestRevision(selectedItem.id, reviewNotes);
      setSelectedItem(null);
      setReviewNotes('');
    }
  };

  return (
    <div className={`space-y-6 ${className}`}>
      {/* Header */}
      <div className="bg-white rounded-2xl border-2 border-black shadow-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-2xl font-black text-gray-900">Agent-Generated Content Review</h2>
            <p className="text-sm text-gray-600 mt-1">
              Review and approve content created by AI agents
            </p>
          </div>
          {pendingCount > 0 && (
            <div className="bg-yellow-100 px-4 py-2 rounded-xl border-2 border-yellow-300">
              <p className="text-sm font-bold text-yellow-700">
                {pendingCount} pending review{pendingCount !== 1 ? 's' : ''}
              </p>
            </div>
          )}
        </div>

        {/* Filters */}
        <div className="flex gap-2">
          {(['all', 'pending', 'approved', 'rejected'] as const).map((status) => (
            <button
              key={status}
              onClick={() => setFilterStatus(status)}
              className={`px-4 py-2 rounded-lg font-bold text-sm border-2 transition-all ${
                filterStatus === status
                  ? 'bg-blue-500 text-white border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]'
                  : 'bg-white text-gray-700 border-gray-300 hover:border-blue-300'
              }`}
            >
              {status.charAt(0).toUpperCase() + status.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Content List */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {filteredItems.length > 0 ? (
          filteredItems.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="bg-white rounded-xl border-2 border-black shadow-md p-4 hover:shadow-lg transition-shadow"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="bg-blue-100 p-2 rounded-lg border-2 border-black">
                    {getIcon(item.type)}
                  </div>
                  <div>
                    <h3 className="font-black text-gray-900">{item.title}</h3>
                    <p className="text-xs text-gray-600">
                      by {item.generatedBy} • {new Date(item.generatedAt).toLocaleDateString()}
                    </p>
                  </div>
                </div>
                {getStatusBadge(item.status)}
              </div>

              <p className="text-sm text-gray-700 mb-3">{item.description}</p>

              {/* Metadata */}
              {item.metadata && (
                <div className="flex flex-wrap gap-2 mb-3">
                  {item.metadata.difficulty && (
                    <span className="px-2 py-1 bg-gray-100 rounded text-xs font-semibold text-gray-700 border border-gray-300">
                      {item.metadata.difficulty}
                    </span>
                  )}
                  {item.metadata.topic && (
                    <span className="px-2 py-1 bg-blue-100 rounded text-xs font-semibold text-blue-700 border border-blue-300">
                      {item.metadata.topic}
                    </span>
                  )}
                </div>
              )}

              {/* Actions */}
              <div className="flex gap-2">
                <Button
                  onClick={() => setSelectedItem(item)}
                  size="sm"
                  variant="outline"
                  className="flex-1 border-2 border-black font-bold"
                >
                  <Eye className="w-4 h-4 mr-2" />
                  Review
                </Button>
                
                {item.status === 'pending' && (
                  <>
                    <Button
                      onClick={() => {
                        setSelectedItem(item);
                        setTimeout(() => handleApprove(), 100);
                      }}
                      size="sm"
                      className="bg-green-500 hover:bg-green-600 text-white border-2 border-black font-bold"
                    >
                      <ThumbsUp className="w-4 h-4" />
                    </Button>
                    <Button
                      onClick={() => setSelectedItem(item)}
                      size="sm"
                      className="bg-red-500 hover:bg-red-600 text-white border-2 border-black font-bold"
                    >
                      <ThumbsDown className="w-4 h-4" />
                    </Button>
                  </>
                )}
              </div>
            </motion.div>
          ))
        ) : (
          <div className="col-span-2 bg-gray-50 rounded-xl border-2 border-gray-300 p-12 text-center">
            <AlertCircle className="w-16 h-16 text-gray-400 mx-auto mb-4" />
            <p className="text-gray-600 font-semibold">
              No content items to review in this category
            </p>
          </div>
        )}
      </div>

      {/* Review Modal */}
      <AnimatePresence>
        {selectedItem && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setSelectedItem(null)}
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className="bg-white rounded-2xl border-2 border-black shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Modal Header */}
              <div className="sticky top-0 bg-white border-b-2 border-black p-6 z-10">
                <div className="flex items-start justify-between">
                  <div>
                    <h3 className="text-2xl font-black text-gray-900 mb-1">
                      {selectedItem.title}
                    </h3>
                    <p className="text-sm text-gray-600">
                      Generated by {selectedItem.generatedBy} on{' '}
                      {new Date(selectedItem.generatedAt).toLocaleString()}
                    </p>
                  </div>
                  <button
                    onClick={() => setSelectedItem(null)}
                    className="text-gray-500 hover:text-gray-700"
                  >
                    <XCircle className="w-6 h-6" />
                  </button>
                </div>
              </div>

              {/* Modal Content */}
              <div className="p-6 space-y-6">
                {/* Content Preview */}
                <div className="bg-gray-50 rounded-xl border-2 border-gray-300 p-4">
                  <h4 className="font-bold text-gray-900 mb-3">Content Preview</h4>
                  <div className="prose prose-sm max-w-none">
                    {typeof selectedItem.content === 'string' ? (
                      <p>{selectedItem.content}</p>
                    ) : (
                      <pre className="text-xs bg-white p-3 rounded border border-gray-300 overflow-x-auto">
                        {JSON.stringify(selectedItem.content, null, 2)}
                      </pre>
                    )}
                  </div>
                </div>

                {/* Learning Objectives */}
                {selectedItem.metadata?.learningObjectives && (
                  <div>
                    <h4 className="font-bold text-gray-900 mb-2">Learning Objectives</h4>
                    <ul className="space-y-1">
                      {selectedItem.metadata.learningObjectives.map((objective, index) => (
                        <li key={index} className="flex items-start gap-2 text-sm text-gray-700">
                          <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
                          <span>{objective}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Review Notes */}
                <div>
                  <label className="block font-bold text-gray-900 mb-2">
                    Review Notes / Feedback
                  </label>
                  <textarea
                    value={reviewNotes}
                    onChange={(e) => setReviewNotes(e.target.value)}
                    placeholder="Add your feedback or notes here..."
                    className="w-full p-3 border-2 border-gray-300 rounded-lg focus:border-blue-500 focus:outline-none resize-none"
                    rows={4}
                  />
                </div>

                {/* Actions */}
                <div className="flex gap-3">
                  <Button
                    onClick={handleApprove}
                    className="flex-1 bg-green-500 hover:bg-green-600 text-white border-2 border-black font-bold"
                  >
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Approve
                  </Button>
                  
                  <Button
                    onClick={handleRequestRevision}
                    disabled={!reviewNotes.trim()}
                    className="flex-1 bg-orange-500 hover:bg-orange-600 text-white border-2 border-black font-bold disabled:opacity-50"
                  >
                    <Edit className="w-4 h-4 mr-2" />
                    Request Revision
                  </Button>
                  
                  <Button
                    onClick={handleReject}
                    disabled={!reviewNotes.trim()}
                    className="flex-1 bg-red-500 hover:bg-red-600 text-white border-2 border-black font-bold disabled:opacity-50"
                  >
                    <XCircle className="w-4 h-4 mr-2" />
                    Reject
                  </Button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
