/**
 * AgentAnalyticsDashboard Component
 * 
 * Teacher/parent dashboard for viewing learning analytics generated by AI agents.
 * Provides insights into student progress, engagement, and learning patterns.
 */

'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
  Brain,
  TrendingUp,
  Target,
  Clock,
  Award,
  AlertTriangle,
  CheckCircle,
  Activity,
  BarChart3,
  PieChart,
} from 'lucide-react';
import { LearningState } from '@/lib/agents/types';
import { globalAgentManager } from '@/lib/agents/agent-manager';

interface AgentAnalyticsDashboardProps {
  studentId: string;
  studentName?: string;
  className?: string;
}

export function AgentAnalyticsDashboard({
  studentId,
  studentName = 'Student',
  className = '',
}: AgentAnalyticsDashboardProps) {
  const [learningState, setLearningState] = useState<LearningState | null>(null);
  const [systemHealth, setSystemHealth] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadAnalytics = async () => {
      try {
        await globalAgentManager.initialize();
        
        const state = globalAgentManager.getLearningState(studentId);
        const health = globalAgentManager.getSystemHealth();
        
        setLearningState(state);
        setSystemHealth(health);
      } catch (error) {
        console.error('Error loading analytics:', error);
      } finally {
        setLoading(false);
      }
    };

    loadAnalytics();
  }, [studentId]);

  if (loading) {
    return (
      <div className={`bg-white rounded-2xl border-2 border-black shadow-lg p-8 ${className}`}>
        <div className="flex items-center justify-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        </div>
      </div>
    );
  }

  if (!learningState) {
    return (
      <div className={`bg-white rounded-2xl border-2 border-black shadow-lg p-8 ${className}`}>
        <div className="text-center">
          <Brain className="w-16 h-16 text-gray-400 mx-auto mb-4" />
          <h3 className="text-xl font-bold text-gray-900 mb-2">No Learning Data Yet</h3>
          <p className="text-gray-600">
            {studentName} hasn't started any learning sessions with the AI agents yet.
          </p>
        </div>
      </div>
    );
  }

  const { knowledgeMap, currentObjectives, engagementMetrics, learningPath } = learningState;

  // Calculate key metrics
  const conceptsArray = knowledgeMap?.concepts ? Object.values(knowledgeMap.concepts) : [];
  const totalConcepts = conceptsArray.length;
  const masteredConcepts = Array.from(knowledgeMap?.masteryLevels?.values() || []).filter(
    level => level.level === 'mastered' || level.level === 'proficient'
  ).length;
  const knowledgeGaps = knowledgeMap?.knowledgeGaps?.length || 0;
  const activeGoals = currentObjectives?.filter(obj => obj.progress < 1).length || 0;
  const completedGoals = currentObjectives?.filter(obj => obj.progress >= 1).length || 0;

  return (
    <div className={`space-y-6 ${className}`}>
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-500 to-purple-500 rounded-2xl border-2 border-black shadow-lg p-6 text-white">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-black mb-2">Learning Analytics for {studentName}</h2>
            <p className="text-blue-100">Powered by AI Agents 🤖</p>
          </div>
          <div className="bg-white/20 backdrop-blur-sm rounded-xl p-4 border-2 border-white/30">
            <Brain className="w-12 h-12" />
          </div>
        </div>
      </div>

      {/* Key Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          icon={<Target className="w-6 h-6" />}
          title="Mastery Progress"
          value={`${masteredConcepts}/${totalConcepts}`}
          subtitle="concepts mastered"
          color="blue"
          trend={masteredConcepts > 0 ? 'up' : 'neutral'}
        />
        
        <MetricCard
          icon={<TrendingUp className="w-6 h-6" />}
          title="Learning Velocity"
          value="1.0x"
          subtitle="speed multiplier"
          color="green"
          trend="neutral"
        />
        
        <MetricCard
          icon={<Activity className="w-6 h-6" />}
          title="Engagement"
          value={`${Math.round((engagementMetrics?.currentLevel || 0.5) * 100)}%`}
          subtitle="current level"
          color="purple"
          trend={(engagementMetrics?.currentLevel || 0.5) > 0.7 ? 'up' : (engagementMetrics?.currentLevel || 0.5) < 0.3 ? 'down' : 'neutral'}
        />
        
        <MetricCard
          icon={<AlertTriangle className="w-6 h-6" />}
          title="Knowledge Gaps"
          value={knowledgeGaps.toString()}
          subtitle="areas to strengthen"
          color="orange"
          trend={knowledgeGaps > 0 ? 'down' : 'neutral'}
        />
      </div>

      {/* Learning Objectives */}
      <div className="bg-white rounded-2xl border-2 border-black shadow-lg p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-purple-100 p-3 rounded-xl border-2 border-black">
            <Target className="w-6 h-6 text-purple-600" />
          </div>
          <div>
            <h3 className="text-xl font-black text-gray-900">Learning Objectives</h3>
            <p className="text-sm text-gray-600">
              {activeGoals} active • {completedGoals} completed
            </p>
          </div>
        </div>

        {currentObjectives && currentObjectives.length > 0 ? (
          <div className="space-y-3">
            {currentObjectives.slice(0, 5).map((objective, index) => (
              <motion.div
                key={objective.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
                className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl border border-gray-200"
              >
                <div className={`p-2 rounded-lg ${
                  objective.progress >= 1
                    ? 'bg-green-100 border-2 border-green-400'
                    : 'bg-blue-100 border-2 border-blue-400'
                }`}>
                  {objective.progress >= 1 ? (
                    <CheckCircle className="w-5 h-5 text-green-600" />
                  ) : (
                    <Target className="w-5 h-5 text-blue-600" />
                  )}
                </div>
                
                <div className="flex-1">
                  <p className="font-bold text-gray-900">{objective.description}</p>
                  <div className="flex items-center gap-3 mt-2">
                    <div className="flex-1 bg-gray-200 rounded-full h-2">
                      <div
                        className={`h-full rounded-full ${
                          objective.progress >= 1
                            ? 'bg-green-500'
                            : 'bg-blue-500'
                        }`}
                        style={{ width: `${objective.progress * 100}%` }}
                      />
                    </div>
                    <span className="text-sm font-bold text-gray-600">
                      {Math.round(objective.progress * 100)}%
                    </span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        ) : (
          <p className="text-gray-500 text-center py-4">No learning objectives set yet</p>
        )}
      </div>

      {/* Knowledge Map */}
      <div className="bg-white rounded-2xl border-2 border-black shadow-lg p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-100 p-3 rounded-xl border-2 border-black">
            <Brain className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h3 className="text-xl font-black text-gray-900">Knowledge Map</h3>
            <p className="text-sm text-gray-600">Concept mastery breakdown</p>
          </div>
        </div>

        {knowledgeMap && knowledgeMap.concepts && Object.keys(knowledgeMap.concepts).length > 0 ? (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {Object.values(knowledgeMap.concepts).slice(0, 12).map((concept, index) => {
              const masteryData = Array.from(knowledgeMap.masteryLevels?.values() || []).find(
                m => m.conceptId === concept.id
              );
              const mastery = masteryData?.level || 'unknown';
              const masteryColors = {
                unknown: 'bg-gray-100 border-gray-300 text-gray-700',
                introduced: 'bg-yellow-100 border-yellow-300 text-yellow-700',
                developing: 'bg-blue-100 border-blue-300 text-blue-700',
                proficient: 'bg-green-100 border-green-300 text-green-700',
                mastered: 'bg-purple-100 border-purple-300 text-purple-700',
              };

              return (
                <motion.div
                  key={concept.id}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: index * 0.03 }}
                  className={`p-3 rounded-lg border-2 ${masteryColors[mastery]}`}
                >
                  <p className="font-bold text-sm">{concept.name}</p>
                  <p className="text-xs mt-1 capitalize">{mastery}</p>
                </motion.div>
              );
            })}
          </div>
        ) : (
          <p className="text-gray-500 text-center py-4">No concepts tracked yet</p>
        )}
      </div>

      {/* Knowledge Gaps */}
      {knowledgeGaps > 0 && knowledgeMap?.knowledgeGaps && (
        <div className="bg-orange-50 rounded-2xl border-2 border-orange-300 shadow-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-orange-100 p-3 rounded-xl border-2 border-black">
              <AlertTriangle className="w-6 h-6 text-orange-600" />
            </div>
            <div>
              <h3 className="text-xl font-black text-gray-900">Areas to Strengthen</h3>
              <p className="text-sm text-gray-600">Identified by AI agents</p>
            </div>
          </div>

          <div className="space-y-2">
            {knowledgeMap.knowledgeGaps.map((gap, index) => (
              <div
                key={index}
                className="flex items-center gap-3 p-3 bg-white rounded-lg border border-orange-200"
              >
                <div className="bg-orange-200 rounded-full w-8 h-8 flex items-center justify-center border border-orange-400">
                  <span className="text-sm font-bold text-orange-700">{index + 1}</span>
                </div>
                <div className="flex-1">
                  <p className="font-bold text-gray-900">{gap.concept}</p>
                  <p className="text-sm text-gray-600">{gap.description}</p>
                </div>
                <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                  gap.severity === 'critical' || gap.severity === 'major'
                    ? 'bg-red-100 text-red-700 border border-red-300'
                    : gap.severity === 'moderate'
                    ? 'bg-orange-100 text-orange-700 border border-orange-300'
                    : 'bg-yellow-100 text-yellow-700 border border-yellow-300'
                }`}>
                  {typeof gap.severity === 'string' ? gap.severity : 'moderate'}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* System Health */}
      {systemHealth && (
        <div className="bg-gray-50 rounded-xl border border-gray-300 p-4">
          <details>
            <summary className="font-bold text-gray-900 cursor-pointer">
              Agent System Status
            </summary>
            <div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
              <div>
                <p className="text-gray-600">Active Agents</p>
                <p className="font-bold text-gray-900">{systemHealth.activeAgents || 0}</p>
              </div>
              <div>
                <p className="text-gray-600">Events Processed</p>
                <p className="font-bold text-gray-900">{systemHealth.eventsProcessed || 0}</p>
              </div>
              <div>
                <p className="text-gray-600">Active Sessions</p>
                <p className="font-bold text-gray-900">{systemHealth.activeSessions || 0}</p>
              </div>
              <div>
                <p className="text-gray-600">Status</p>
                <p className="font-bold text-green-600">{systemHealth.status || 'Healthy'}</p>
              </div>
            </div>
          </details>
        </div>
      )}
    </div>
  );
}

// Metric Card Component
interface MetricCardProps {
  icon: React.ReactNode;
  title: string;
  value: string;
  subtitle: string;
  color: 'blue' | 'green' | 'purple' | 'orange';
  trend?: 'up' | 'down' | 'neutral';
}

function MetricCard({ icon, title, value, subtitle, color, trend = 'neutral' }: MetricCardProps) {
  const colorSchemes = {
    blue: 'from-blue-50 to-cyan-50 border-blue-300',
    green: 'from-green-50 to-teal-50 border-green-300',
    purple: 'from-purple-50 to-pink-50 border-purple-300',
    orange: 'from-orange-50 to-red-50 border-orange-300',
  };

  const iconColors = {
    blue: 'bg-blue-100 text-blue-600',
    green: 'bg-green-100 text-green-600',
    purple: 'bg-purple-100 text-purple-600',
    orange: 'bg-orange-100 text-orange-600',
  };

  const trendIcons = {
    up: '📈',
    down: '📉',
    neutral: '➡️',
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`bg-gradient-to-br ${colorSchemes[color]} rounded-xl border-2 shadow-md p-4`}
    >
      <div className="flex items-start justify-between mb-3">
        <div className={`${iconColors[color]} p-2 rounded-lg border-2 border-black`}>
          {icon}
        </div>
        <span className="text-lg">{trendIcons[trend]}</span>
      </div>
      <p className="text-sm font-bold text-gray-700 mb-1">{title}</p>
      <p className="text-3xl font-black text-gray-900 mb-1">{value}</p>
      <p className="text-xs text-gray-600">{subtitle}</p>
    </motion.div>
  );
}
